src/courses/urls.py
from rest_framework.routers import SimpleRouter

from courses.views import CourseSignupView, CourseViewSet, TestView

app_name = "courses"

router = SimpleRouter()
router.register("courses", CourseViewSet)
router.register("course-signups", CourseSignupView, basename="course_signups")
router.register("tst", TestView, basename="tst")

urlpatterns = router.urls

src/frontend/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from .views import ActivationView

app_name = "frontend"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="index.html", extra_context={"running_prod": not settings.DEBUG}
        ),
    ),
    path(
        "activation/<str:uid>/<str:token>/",
        ActivationView.as_view(extra_context={"running_prod": not settings.DEBUG}),
    ),
    path(
        "gdpr/",
        TemplateView.as_view(
            template_name="privacy_policy.html", extra_context={"running_prod": not settings.DEBUG}
        ),
    ),
    path(
        "login/",
        TemplateView.as_view(
            template_name="login.html", extra_context={"running_prod": not settings.DEBUG}
        ),
        name="login",
    ),
    path(
        "courses/",
        TemplateView.as_view(
            template_name="courses.html", extra_context={"running_prod": not settings.DEBUG}
        ),
    ),
    path(
        "courses/<int:id>/",
        TemplateView.as_view(
            template_name="course_details.html", extra_context={"running_prod": not settings.DEBUG}
        ),
    ),
]

src/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from aws.views import health_check

schema_view = get_schema_view(
    openapi.Info(
        title="Black Sheep Codes Documentation",
        default_version="V1",
        license=openapi.License(
            name="GNU GPL V 3", url="https://www.gnu.org/licenses/gpl-3.0.en.html"
        ),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("frontend.urls")),
    re_path("health/", health_check),
    path("admin/", admin.site.urls),
    path("api/v1/auth/", include("djoser.urls")),
    path("api/v1/auth/", include("djoser.urls.authtoken")),
    path("api/v1/", include("courses.urls")),
    path("api/v1/", include("lessons.urls")),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^swagger(?P<format>\.json|\.yaml)$",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        re_path(
            r"^swagger/$", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"
        ),
        re_path(r"^docs/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    ]


if not settings.AWS_STORAGE_BUCKET_NAME:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/frontend/views.py
import requests
from django.conf import settings
from django.http import HttpResponseBadRequest
from django.views.generic import TemplateView
from rest_framework import status


class ActivationView(TemplateView):
    template_name = "activation.html"
    extra_context = {"running_prod": not settings.DEBUG}

    def get(self, request, uid, token, **kwargs):
        payload = {"uid": uid, "token": token}
        response = requests.post(f"{settings.HOST}api/v1/auth/users/activation/", data=payload)
        if response.status_code != status.HTTP_204_NO_CONTENT:
            return HttpResponseBadRequest(b"Bad request")
        return super().get(request)

src/frontend/templates/activation.html
{% extends 'base.html' %}

{% block content %}
    <p>Your account has been activated. You can now <a href="{% url 'frontend:login' %}" class="login-link">log in</a></p>
    <p>Happy hacking!</p>
{% endblock content %}

{% block scripts %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/activation.css' %}">
{% endblock scripts %}

src/frontend/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Black Sheep Learns</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

    {% load static %}
    <!-- Header -->
    <div class="header bg-blue p-3 container-fluid">
        <div class="row">
            <div class="col-md-11">
                <div class="pl-3">
                    <a href="/courses/">
                        <img src="{% static 'icons/graduation-cap.svg' %}" width="16" height="16" class="bi bi-github">
                        Black Sheep Learns
                    </a>
                </div>
            </div>
            
            <div class="col-md-1 text-right">
                <a href="https://github.com/gonczor/black-sheep-learns" id="github-link">
                    <img src="{% static 'icons/github.svg' %}" width="16" height="16" class="bi bi-github">
                </a>
                <a href="https://twitter.com/" id="twitter-link">
                    <img src="{% static 'icons/twitter.svg' %}" width="16" height="16" class="bi bi-github">
                </a>
            </div>
        </div>
    </div>

    <!-- Content -->
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>



    <!-- Footer -->
    <div class="container-fluid">
        <div class="row">
            <footer class="footer bg-blue text-center p-2">
                <p>
                    <span>
                        Contact me:
                        <a href="mailto:gonczor@blacksheep.pl">gonczor@blacksheephacks.pl</a>
                    </span>
                    <span class="p-1"> | </span>
                    <span>
                        <a href="/gdpr/">Terms and conditions, privacy policy</a>
                    </span>
                    <span class="p-1"> | </span>
                    <span>
                        <a href="https://github.com/gonczor/black-sheep-learns" id="github-link">
                            View on GitHub:
                            <img src="{% static 'icons/github.svg' %}" width="16" height="16" class="bi bi-github"></img>
                        </a>
                    </span>
                </p>
            </footer>
        </div>
    </div>

    <!-- Static -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/error_handler.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

src/frontend/templates/course_details.html
{% extends 'base.html' %}

{% block content %}
{% verbatim %}

<div id="app">
    <div class="container">
        <div class="row">
            <div class="col-lg-2">
                <div class="m-2 border rounded">
                    <a href="/courses/" class="return-link">
                        <div class="p-2 text-center fw-bold">Back to all courses</div></a>
                </div>
                <div class="m-2 border rounded">
                    <div class="text-center">
                        <div v-for="section in sections">
                            <div class="fw-bold bg-blue">
                                {{ section.name }}
                            </div>
                            <div v-for="(lesson, index) in section.lessons">
                                <div v-if="index !== section.lessons.length-1" v-on:click="getLessonDetails" class="text-center lesson-element lesson-element-bordered" :data-lesson-id="lesson.id">
                                    {{ lesson.name }} <span v-if="lesson.isComplete">&check;</span>
                                </div>
                                <div v-if="index === section.lessons.length-1" v-on:click="getLessonDetails" class="text-center lesson-element" :data-lesson-id="lesson.id">
                                    {{ lesson.name }} <span v-if="lesson.isComplete">&check;</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-10">
                <div class="m-2 p-2 border rounded" style="min-height: 64px">
                    <div class="container" v-if="lessonDetails !== null">
                        <div class="row m-2">
                            <h2 class="text-center align-self-center text-uppercase">
                                {{ lessonDetails.name }}
                            </h2>
                        </div>
                        <hr>
                        <div class="row m-2">
                            <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                                <div v-if="isLesson()">
                                    <div class="text-center m-2">
                                        <video controls width="400px" :src="lessonDetails.video" style="min-width: 400px"></video>
                                    </div>
                                </div>
                                <div v-if="isTest()">
                                    <div v-if="!isBeyondLastQuestion()">
                                        <fieldset :id="currentTestQuestion.id">
                                            <legend>{{ currentTestQuestion.text }}</legend>
                                            <div v-for="answer in currentTestQuestion.answers">
                                                <input type="radio" name="answer" :id="answer.id" :value="answer.id" class="m-2" @click="selectAnswer" /><label :for="answer.id" v-html="answer.text" class="m-2" :id="'answer-' + answer.id"></label><br />
                                            </div>
                                            <button class="btn bg-blue m-2" v-on:click="checkAnswer">Check</button>
                                            <button class="btn bg-light m-2" v-on:click="moveToNextQuestion()">Next &#8594;</button>
                                            <button class="btn bg-light m-2" v-on:click="moveToPreviousQuestion()">Previous &#8592;</button>
                                        </fieldset>
                                    </div>
                                    <div v-if="isBeyondLastQuestion()">
                                        This was the last question. Your score is:
                                    </div>
                                    <div class="m-2 text-center">
                                        {{ getCorrectAnswersCounter() }}
                                    </div>
                                </div>
                                <div class="m-2 text-justify">{{ lessonDetails.description }}</div>
                                <div v-if="lessonDetails.additionalMaterials" class="text-center bg-blue">
                                    <a :href="lessonDetails.additionalMaterials">Download additional materials here.</a>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="m-2" v-if="!lessonDetails.isComplete" v-on:click="markLessonAsComplete()">
                                    <button class="btn btn-complete">Complete</button>
                                </div>
                                <div class="m-2" v-if="lessonDetails.isComplete" v-on:click="revertMarkLessonAsComplete()">
                                    <button class="btn btn-danger">Incomplete</button>
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <!-- Header -->
                            <div class="row m-2">
                                <h2 class="text-center align-self-center">
                                    Comments
                                </h2>
                            </div>
                            <hr>
                            <!-- write comment -->
                            <div class="row m-2">
                                <div class="m-2">
                                    <textarea v-model="commentText" style="width: 100%" placeholder="Share your thoughts">{{ commentText }}</textarea>
                                </div>
                                <div class="m-2">
                                    <button class="btn bg-blue right" v-on:click="sendComment()">Send comment</button>
                                </div>
                            </div>
                            <hr>
                            <!-- List -->
                            <div class="row m-2">
                                <div v-for="comment in comments">
                                    <div class="comment-box">
                                        {{ comment.text }}
                                    </div>
                                    <div class="comment-author">
                                        author: {{ comment.author }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endverbatim %}
{% endblock content %}

{% block scripts %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/course_details.css' %}">
    {% if running_prod %}
        <script src="https://unpkg.com/vue@3.2.6/dist/vue.global.prod.js"></script>
    {% else %}
        <script src="https://unpkg.com/vue@3.2.6"></script>
    {% endif %}
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/course_details.js' %}"></script>
{% endblock scripts %}

src/frontend/templates/courses.html
{% extends 'base.html' %}

{% block content %}
{% verbatim %}

<div id="vueApp">
    <div class="container">
        <div class="row" id="courses-list">
            <div class="col-lg-2">
                <div class="m-2 border rounded">
                    <div class="p-2 text-center fw-bold">
                        Available courses:
                    </div>
                    <div v-for="course in courses">
                        <div class="text-center course-element" v-on:click="getCourseDetails" :data-id="course.id">
                            {{ course.name }}
                        </div>
                    </div>
                </div>
                <div class="m-2 border rounded">
                    <div class="p-2 text-center fw-bold">
                        Your courses:
                    </div>
                    <div v-for="course in ownCourses">
                        <div class="text-center course-element" v-on:click="redirectToDetails" :data-id="course.id">
                            {{ course.name }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-10">
                <div class="p-2 m-2 border rounded course-details-container">
                    <div class="container" v-if="hasDetails()">
                        <div class="row m-2">
                            <div class="col-lg-3 text-center">
                                <img :src="courseDetails.image">
                            </div>
                            <div class="col-lg-6 text-center align-self-center">
                                <h1>{{ courseDetails.name }}</h1>
                            </div>
                            <div class="col-lg-3 text-center align-self-center">
                                <div >
                                    <button v-on:click="signUpForCourse" class="btn btn-signup hover-shadow bg-blue">Join Course</button>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="row m-2">
                            <div class="col-lg-12">
                                {{ courseDetails.description }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="signupToast" class="toast">Successfully signed up for the course.</div>
</div>

{% endverbatim %}
{% endblock content %}

{% block scripts %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/courses.css' %}">
    {% if running_prod %}
        <script src="https://unpkg.com/vue@3.2.6/dist/vue.global.prod.js"></script>
    {% else %}
        <script src="https://unpkg.com/vue@3.2.6"></script>
    {% endif %}
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script src="{% static 'js/courses.js' %}"></script>
{% endblock scripts %}

src/frontend/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% include 'inline_redirect.html' %}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="border rounded p-2 m-2">
                <div>
                    <p class="greetings">
                        Hi!
                    </p>
                    <p class="greetings">
                        I'm happy to see you here. Welcome on the Black Sheep Learns platform built by developers for... Wannabe developers ;-)
                    </p>
                    <p class="greetings">
                        I know how it feels when you first start learning the art of programming: lack of ideas about where to begin, enigmatic documentation, possibly lack of money for bootcamps. I've been there and if you are at this point right now, let me give you a helping hand.
                    </p>
                </div>
                <div align="center">
                    <video controls width="300px">
                        <source src="https://blacksheep-dev2.s3-eu-west-1.amazonaws.com/static/IMG_5515.mov" type="video/mp4" />
                    </video>
                </div>
                <div>
                    <p class="greetings">
                        The aim of this platform is to provide a cheap, yet efficient way of learning programming. From installing necessary tools, through making the first steps up to mastering the necessary skills to let you apply for your first job.
                    </p>
                    <p class="greetings">
                        Why should you try it out?
                        <ul>
                            <li>You pay less than in bootcamp: get free lessons with basics. Subscribe for the paid content only if you feel it's valuable</li>
                            <li>You get more than on Youtube: check your knowledge with tests and monitor your improvements.</li>
                            <li>You can share your thoughts with other students: discuss your problems and solutions in a beginner-friendly environment.</li>
                            <li>Your instructor was at the same point as you are now. I have nothing to hide and you can check this project on GitHub.</li>
                        </ul>
                    </p>
                    <p class="greetings">
                        So, are you joining the herd?
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            {% include 'login_form.html' %}
        </div>
        <div class="col-lg-3">
            {% include 'signup_form.html' %}
        </div>
    </div>
</div>
<div id="accountCreationToast" class="toast">Successfully created the account. Please see activation email.</div>
{% endblock content %}
{% block scripts %}
    {% load static %}
    <script src="{% static 'js/auth.js' %}"></script>
{% endblock scripts %}

src/frontend/templates/inline_redirect.html
<script>
  function redirectIfLoggedIn(){
    let token = localStorage.getItem("token");
    if (token === null){
      // No token, no redirect.
      return;
    }
    const XHR = new XMLHttpRequest();
    XHR.open( "GET", "/api/v1/auth/users/me/" );
    XHR.setRequestHeader('Content-Type', 'application/json;');
    XHR.setRequestHeader('Authorization', 'Token ' + token);
    XHR.addEventListener("load", (event) => {
      if (event.target.status === 200){
        window.location = "/courses/";
      } else {
        // Token is invalid, we can remove it.
        localStorage.removeItem("token");
      }
    });
    XHR.send();
  }
  redirectIfLoggedIn();
</script>

src/frontend/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% include 'inline_redirect.html' %}
<div class="container">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-3">
            {% include 'login_form.html' %}
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>
   
{% endblock content %}
{% block scripts %}
    {% load static %}
    <script src="{% static 'js/auth.js' %}"></script>
{% endblock scripts %}

src/frontend/templates/login_form.html
<form id="loginForm">
    <div class="form-group border rounded p-2 m-2">
        <p class="text-center">Login</p>
        <p><label for="username">Username:</label></p>
        <p><input type="text" name="username" id="username"></p>
        <p><label for="password">Password:</label></p>
        <p><input type="password" name="password" id="password"></p>
        <p><input type="submit" value="Sign In!" class="btn btn-success"></p>
    </div>
</form>

src/frontend/templates/privacy_poicy.html
{% extends 'base.html' %}

{% block content %}
    <h1>Terms, conditions and privacy policy</h1>
    <p>
        The administrator of courses.blacksheephacks.pl is Black Sheep Wiktor Gonczaronek registered in Poland
        under VAT number (Numer Identyfikacji Podatkowej) 6711778174, from now on referred as BLACK SHEEP.
    </p>
    <p>
        BLACK SHEEP creates the platform service, available under the address courses.blacksheephacks.pl. The access to the
        platform is restricted to registered users. By using the platform users acknowledge that they are familiar with the following rules.
    </p>
    <p>
        During registration following personal information is required: email address. This data is collected in order to
        avoid spam and necessary features like password reset.
        Users may provide additional personal data like first and last name, though this is not required.
    </p>
    <p>
        BLACK SHEEP may process other personal data like the IP address in order to provide security and analyze the
        way users interact with the service in order to provide stability and efficiency.
    </p>
    <p>
        The courses.blacksheephacks.pl platform is an open source project and therefore the exact details of how the personal data is processed
        can be found in the code.
    </p>
    <p>
        The service uses AWS infrastructure located in Germany and Ireland to serve the application, store and process data.
    </p>
    <p>
        Users have right to see what personal data is processed, alter it and ask to delete it. In order to perform such
        requests, please email your inquiry to admin@blacksheephacks.pl.
    </p>
    <p>
        BLACK SHEEP may restrict access to the platform if malicious actions are detected. Those include: rude, abusive
        language, threats towards other users, spam.
    </p>
    <p>
        On the service courses.blacksheephacks.pl cookies are not used. In order to provide technical functions like logging in,
        tokens stored by the browser in local storage are used.
    </p>
    <p>
        Advertising may be used in order to provide revenue. This includes sites like Ethical Ads. In order to find out how
        this service uses personal data, please read their <a href="https://www.ethicalads.io/privacy-policy/"> privacy policy</a>
    </p>
{% endblock %}

src/frontend/templates/privacy_policy.html
{% extends 'base.html' %}

{% block content %}
    <h1>Terms, conditions and privacy policy</h1>
    <p>
        The administrator of courses.blacksheephacks.pl is Black Sheep Wiktor Gonczaronek registered in Poland
        under VAT number (Numer Identyfikacji Podatkowej) 6711778174, from now on referred as BLACK SHEEP.
    </p>
    <p>
        BLACK SHEEP creates the platform service, available under the address courses.blacksheephacks.pl. The access to the
        platform is restricted to registered users. By using the platform users acknowledge that they are familiar with the following rules.
    </p>
    <p>
        During registration following personal information is required: email address. This data is collected in order to
        avoid spam and necessary features like password reset.
        Users may provide additional personal data like first and last name, though this is not required.
    </p>
    <p>
        BLACK SHEEP may process other personal data like the IP address in order to provide security and analyze the
        way users interact with the service in order to provide stability and efficiency.
    </p>
    <p>
        The courses.blacksheephacks.pl platform is an open source project and therefore the exact details of how the personal data is processed
        can be found in the code.
    </p>
    <p>
        The service uses AWS infrastructure located in Germany and Ireland to serve the application, store and process data.
    </p>
    <p>
        Users have right to see what personal data is processed, alter it and ask to delete it. In order to perform such
        requests, please email your inquiry to admin@blacksheephacks.pl.
    </p>
    <p>
        BLACK SHEEP may restrict access to the platform if malicious actions are detected. Those include: rude, abusive
        language, threats towards other users, spam.
    </p>
    <p>
        On the service courses.blacksheephacks.pl cookies are not used. In order to provide technical functions like logging in,
        tokens stored by the browser in local storage are used.
    </p>
    <p>
        Advertising may be used in order to provide revenue. This includes sites like Ethical Ads. In order to find out how
        this service uses personal data, please read their <a href="https://www.ethicalads.io/privacy-policy/"> privacy policy</a>
    </p>
{% endblock %}

src/frontend/templates/signup_form.html
<form id="accountCreationForm" class="form-group border rounded p-2 m-2 bg-blue">
        <p class="text-center">Create an account</p>
        <p><label for="username">Username:</label></p>
        <p><input type="text" name="username" id="username"></p>
        <p><label for="email">Email:</label></p>
        <p><input type="email" name="email" id="email"></p>
        <p><label for="password">Password:</label></p>
        <p><input type="password" name="password" id="password"></p>
        <p><label for="rePassword">Confirm password:</label></p>
        <p><input type="password" name="rePassword" id="rePassword"></p>
        <p><input type="submit" value="Sign Up!" class="btn btn-success"></p>
</form>